### ISSUE TITLE
Please give some gamma_crf_train's images.

### ISSUE THREAD

**Issue by efss24** [HiLab-git/HAMIL#2]
Hi, I am interested in your work. But there are some questions,I would be very grateful if you could help me with the answer.
①when I run generate_bg_masks.py , in line "out_remove = Image.fromarray(out_remove)" , I meet a TypeError:Cannot handle this data type: (1, 1, 3), |b1.So, I add "out_remove = out_remove.astype(np.uint8)"before it,than it works.
②But i confused that the images gengrated in this code are all balck images.So,could you give me some gamma_crf_train's images.
③ img_open_crf What's the use of img_open_crf's  images

**Comment by lanfz2000** [comment]
for 1, maybe it's Library version problem;
for 2, I will show one example, if you would leave your email address. 
for 3, use CRF function to refine the gamma transformed images

**Comment by lanfz2000** [comment]
For 2, it converts the RGB to gray and use gamma transform on it, it is still gray, then use CRF and argmax on it, you will get foreground and background.

**Comment by cool-breeze-and-rain** [comment]
@lanfz2000 hello，can you give me some  gamma_crf_train's images?  my email is 1583249571@qq.com

**Comment by Albertchamberlain** [comment]
Hello, can you give me some gamma_crf_train images? My email is albert7king@gmail.com

**Comment by Albertchamberlain** [comment]
> For 2, it converts the RGB to gray and use gamma transform on it, it is still gray, then use CRF and argmax on it, you will get foreground and background.

Hello, can you give me some gamma_crf_train images? My email is albert7king@gmail.com

**Comment by Albertchamberlain** [comment]
> Hi, I am interested in your work. But there are some questions,I would be very grateful if you could help me with the answer. ①when I run generate_bg_masks.py , in line "out_remove = Image.fromarray(out_remove)" , I meet a TypeError:Cannot handle this data type: (1, 1, 3), |b1.So, I add "out_remove = out_remove.astype(np.uint8)"before it,than it works. ②But i confused that the images gengrated in this code are all balck images.So,could you give me some gamma_crf_train's images. ③ img_open_crf What's the use of img_open_crf's images

Hi，have you successfully reproduced it ？
